"""PostgreSQL user repository (stub).

Placeholder for a future PostgreSQL-backed user repository
implementation conforming to the UserRepository protocol.
"""

from pydantic import EmailStr


class PostgresUserRepository:

    async def get_by_email(self, email: EmailStr): ...

    async def get_by_id(self, user_id: str): ...

    async def update_user(self, user_id: str, data: dict): ...
    async def delete_user(self, user_id: str): ...
    async def create_user(self, data: dict): ...
    async def get_users(self): ...
